#!/usr/bin/env tsx
/**
 * 📊 Report Generator — Generate markdown reports from analyzed data
 *
 * Usage:
 *   npm run report
 */
import 'dotenv/config';
import chalk from 'chalk';
import { ensureDataDirs, loadAllAnalyses, loadAllHuntResults, saveReport } from '../lib/storage.js';
import { log, formatNumber } from '../lib/utils.js';
import type { ProjectAnalysis } from '../types/index.js';

async function main() {
  await ensureDataDirs();

  log.header('📊 天工报告生成器 — Report Generator');

  const analyses = await loadAllAnalyses();
  const huntResults = await loadAllHuntResults();

  if (analyses.length === 0) {
    log.warn('No analyses found. Run batch analyzer first.');
    log.info(`${chalk.cyan('npm run batch -- --top=20')}`);
    return;
  }

  log.info(`Generating report from ${analyses.length} analyses...`);

  // Group by category
  const byCategory = new Map<string, ProjectAnalysis[]>();
  for (const a of analyses) {
    const cat = a.category || 'uncategorized';
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat)!.push(a);
  }

  // Sort each category by composite score
  for (const [, items] of byCategory) {
    items.sort((a, b) => b.temc.composite - a.temc.composite);
  }

  // Build markdown
  const date = new Date().toISOString().split('T')[0];
  let md = `# 🏗️ 天工代码情报 — GitHub Scan Report\n`;
  md += `> Generated: ${date} | Projects Scanned: ${huntResults.length} | Analyzed: ${analyses.length}\n\n`;
  md += `---\n\n`;

  // Overall Top 10
  const top10 = [...analyses].sort((a, b) => b.temc.composite - a.temc.composite).slice(0, 10);

  md += `## 🏆 Top 10 Overall\n\n`;
  md += `| # | Project | ★ Stars | TEMC | License | Decomp | Commercial Potential |\n`;
  md += `|---|---------|--------|------|---------|--------|---------------------|\n`;

  top10.forEach((a, i) => {
    const licenseEmoji = a.licenseRisk === 'safe' ? '✅' : a.licenseRisk === 'dangerous' ? '🔴' : '🟡';
    md += `| ${i + 1} | [${a.fullName}](${a.url}) | ${formatNumber(a.stars)} | **${a.temc.composite}** (T${a.temc.T}/E${a.temc.E}/M${a.temc.M}/C${a.temc.C}) | ${licenseEmoji} ${a.license || '?'} | ${a.decomposability}/10 | ${a.commercialPotential} |\n`;
  });

  md += `\n---\n\n`;

  // Per category
  for (const [catId, items] of byCategory) {
    const catName = getCategoryName(catId);
    md += `## ${catName} (${items.length} projects)\n\n`;

    for (const a of items.slice(0, 10)) {
      const licenseEmoji = a.licenseRisk === 'safe' ? '✅' : a.licenseRisk === 'dangerous' ? '🔴' : '🟡';

      md += `### ${a.fullName} ★${formatNumber(a.stars)}\n`;
      md += `- **Tech Stack**: ${a.techStack}\n`;
      md += `- **License**: ${licenseEmoji} ${a.license || 'Unknown'} (${a.licenseRisk})\n`;
      md += `- **TEMC**: T=${a.temc.T} E=${a.temc.E} M=${a.temc.M} C=${a.temc.C} | **Composite: ${a.temc.composite}**\n`;
      md += `- **Decomposability**: ${a.decomposability}/10\n`;
      md += `- **Commercial Potential**: ${a.commercialPotential}\n`;
      md += `- **Target Customer**: ${a.targetCustomer}\n`;
      md += `- **Pricing**: ${a.pricingEstimate}\n`;

      if (a.coreModules.length > 0) {
        md += `- **Core Modules**:\n`;
        a.coreModules.forEach(m => { md += `  - ${m}\n`; });
      }

      if (a.strengths.length > 0) {
        md += `- **Strengths**: ${a.strengths.join('; ')}\n`;
      }
      if (a.weaknesses.length > 0) {
        md += `- **Weaknesses**: ${a.weaknesses.join('; ')}\n`;
      }

      md += `\n`;
    }

    md += `---\n\n`;
  }

  // Stats footer
  md += `## 📊 Statistics\n\n`;
  md += `- Total projects hunted: ${formatNumber(huntResults.length)}\n`;
  md += `- Projects analyzed: ${analyses.length}\n`;
  md += `- Categories: ${byCategory.size}\n`;

  const avgComposite = Math.round(analyses.reduce((s, a) => s + a.temc.composite, 0) / analyses.length);
  md += `- Average composite score: ${avgComposite}\n`;

  const safeCount = analyses.filter(a => a.licenseRisk === 'safe').length;
  md += `- License safe: ${safeCount}/${analyses.length} (${Math.round(safeCount / analyses.length * 100)}%)\n`;

  md += `\n---\n`;
  md += `*Generated by 天工引擎 v3.0*\n`;

  // Save
  await saveReport(md);

  log.success(`Report generated: reports/github-scan-${date}.md`);
  log.info(`${analyses.length} projects across ${byCategory.size} categories`);
}

function getCategoryName(id: string): string {
  const names: Record<string, string> = {
    'saas-templates': '💻 SaaS Templates',
    'ai-security': '🛡️ AI Security',
    'ai-tools': '🤖 AI Tools',
    'agent-frameworks': '🧠 Agent Frameworks',
    'solo-tools': '🚀 One-Person Company Tools',
    'landing-marketing': '🎨 Landing Pages & Marketing',
    'auth-payments': '🔐 Auth & Payments',
    'custom': '🔍 Custom Search',
  };
  return names[id] || `📁 ${id}`;
}

main().catch(err => {
  log.error(`Fatal: ${err.message}`);
  process.exit(1);
});
